version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "85:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php
        networks:
            - app-network

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
        networks:
            - app-network

    mysql:
        image: mysql:8.0.33
        platform: linux/arm64/v8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8085:80
        networks:
            - app-network

    mailhog:
        image: axllent/mailpit:latest
        platform: linux/arm64/v8
        ports:
            - "1028:1025"  # SMTP (ポート1025が使用中のため1028に変更)
            - "8027:8025"  # Web UI (ポート8025が使用中のため8027に変更)
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
